### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by thibolepilote** [senghoo/modsecurity-go#2]
Hi, 

The link you provided for libmodsecurity dependency leads to a 404 ... :-(

Is there anyway to have this dependency fixed any way else?
Or is there a way to use your code without libmodsecurity?

Thk you

**Comment by senghoo** [comment]
libmodsecurity seems to merged into [modsecurity v3 master](https://github.com/SpiderLabs/ModSecurity/tree/v3/master).
But this repository is not working now.

**Comment by thibolepilote** [comment]
Ok, thanks! I'll try and use the v3 master!
Do you plan to have it working? And do you know why it isn't working?

**Comment by senghoo** [comment]
sorry, no plan at this time.
When i write this project, libmodsecurity seems not working well, so I'm stoped develop.

**Comment by thibolepilote** [comment]
Ok, no problem! ;-)
