### ISSUE TITLE
NewSecLangScannerFromString()'s package is wrong in README

### ISSUE THREAD

**Issue by hsluoyz** [senghoo/modsecurity-go#5]
https://github.com/senghoo/modsecurity-go/blob/9c340a70bdfaab9c4e3e27ff55fa9195b5d48060/README.md#seclang-parsing

```go
import "github.com/senghoo/modsecurity-go/libmodsecurity/seclang"

var rules = `<<<some modsecurity rules>>`
scaner := seclang.NewSecLangScannerFromString(rules)
d, err := scaner.AllDirective()
if err != nil {
	panic(err)
}
fmt.Printf("%#v\n", d)
```

`NewSecLangScannerFromString()` is actually defined in `parser`.

**Comment by senghoo** [comment]
I have updated readme.
thanks.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/senghoo/modsecurity-go/commit/bdd85ba193f338b1a9a53fcab6e02f7043c16167

**Comment by hsluoyz** [comment]
Thanks!
